version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - springBoot
  springBoot:
    image: 'blog-api-docker.jar'
    container_name: springBoot
    ports:
      - "8080:8080"
    depends_on:
      - postgredb
#    links:
#      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgredb:
    image: postgres
    container_name: postgredb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
#    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
