version: "3.8"
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - springBoot
  springBoot:
    image: 'shopping-mall-webapp.jar'
    container_name: springBoot
    ports:
      - "8080:8080"
    depends_on:
      - postgredb
#    links:
#      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgredb:
    image: postgres
    container_name: postgredb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres\
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5555:80"
    volumes:
      - ./pgadmin/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=the2sang@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - TZ=Asia/Seoul
    depends_on:
      - postgredb
networks:
  postgredb:
    driver: bridge
